openapi: 3.0.1
info:
  title: WeatherServiceAPI
  description: API Definition of WeatherServiceAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/weather
paths:
  /{city}:
    get:
      parameters:
      - name: city
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
